version: "3"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.production
    command: bash -c 'sleep 10 && npm test'
    image: clifrise/devops-for-programmers-project-lvl1 
    depends_on:
      - "db"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"