version: "3"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    command: npm test
    image: clifrise/devops-for-programmers-project-lvl1 
    depends_on:
      - "db"

  db:
    image: postgres:latest
    restart: always
    environment:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
    
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: