version: "3.9"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.production
    command: bash -c 'sleep 3 && npm test'
    image: clifrise/devops-for-programmers-project-lvl1 
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d {DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5